version: '3.8'
services:
  keydb:
    container_name: keydb
    image: eqalpha/keydb:latest
    restart: always
    ports:
      - '6379:6379'
    command: keydb-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - keydb:/data

  # Use to observe redis in development environment
  # source: https://redis.io/docs/stack/get-started/install/docker/
  #redis-stack:
    #image: redis/redis-stack:latest
    #restart: always
    #depends_on:
      #- redis
    #ports:
      #- '6379:6379'
      #- '8001:8001'

volumes:
  keydb:
    driver: local
